# Chai 配置文件：五笔字型 98 版

info:
  id: untitled
  name: 未命名
  version: "0.1"
  author: 无名氏
  description: 用于初始化

degenerator:
  - 笔画序列
  - 笔画拓扑

selector:
  - 笔顺优先
  - 根少优先
  - 能连不交、能散不连
  - 取大优先

classifier:
  '1': [横, 提]
  '2': [竖, 竖钩]
  '3': [撇]
  '4': [点, 捺]
  '5': [横钩, 横撇, 横折, 横折钩, 横斜钩, 横折提, 横折折, 横折弯, 横撇弯钩, 横折弯钩, 横折折撇, 横折折折, 横折折折钩,
      竖提, 竖折, 竖弯, 竖弯钩, 竖折撇, 竖折折钩, 竖折折,
      撇点, 撇折, 弯钩, 斜钩]

roots: [
  二, 三, 干, 王, 戋, 土, 士, 工, 十, 木, 丁, 扌, 耳, 寸, 古, 廿, 艹, 其, 西, 雨, 五, 石, 大, 厂, 豕, 廾, 匚, 七, 弋, 戈, 
  止, 刂, 小, 卜, 冂, 皿, 四, 山, 田, 口, 足, 囗, 贝, 且, 日, 曰, 目, 虫, 巾, 水, 
  手, 禾, 气, 金, 钅, 竹, 白, 臼, 川, 彳, 彡, 舟, 斤, 勹, 八, 人, 豸, 亻, 攵, 夂, 夕, 匕, 犭, 几, 儿, 月, 用, 九, 
  方, 言, 门, 米, 讠, 亠, 冫, 丬, 广, 疒, 文, 立, 心, 忄, 宀, 衤, 礻, 之, 辶, 冖, 火, 灬, 氵, 
  弓, 彐, 尸, 已, 己, 巳, 凵, 也, 巴, 卩, 阝, 子, 孑, 了, 刀, 乃, 力, 女, 又, 厶, 廴, 马, 幺, 纟
]

aliaser: {}
